format = """
[ ](blue)$directory$git_branch$git_status
$username$hostname$sudo$character
"""

right_format = """
$cmd_duration$time
"""

add_newline = true

[character]
success_symbol = "[↪](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
format = "[](#2a7fad)[ $duration ]($style)"
min_time = 0
show_milliseconds = true
style = "bg:#2a7fad bold #ffffff"

[directory]
truncation_length = 100
truncate_to_repo = false
read_only = " "

[git_branch]
style = "bold #adff2f"

[git_status]
format = "[$all_status$ahead_behind]($style) "
conflicted = '\[=\]'
ahead = '[\[⇡\]](bold #adff2f)'
behind = '\[⇣\]'
diverged = '\[⇕\]'
up_to_date = ""
untracked = '\[?\]'
stashed = '\[$\]'
modified= '\[!\]'
staged = '[\[+\]](bold #ffa500)'
renamed = '[\[»\]](bold #ffa500)'
deleted = '\[✘\]'

[hostname]
format = 	"@[$ssh_symbol$hostname]($style) "
style = "bold #6495ed"
ssh_only = false

[sudo]
disabled = false
format = "[$symbol]($style) "
symbol = "\\[S\\]"

[time]
disabled = false
format = "[](bg:#2a7fad #ffffff)[ $time]($style)"
time_format = "%Y-%m-%d %T"
style = "bg:#ffffff bold #696969"

[username]
format = "[$user]($style)"
show_always = true
style_user = "bold #b0c4de"
